### ISSUE TITLE
Debug note in Think (puzzle spoilers)

### ISSUE THREAD

**Issue by jaclynlibrarian** [andrewschultz/low-key-learny-jokey-journey#29]
I ran into a debug note in THINK concerning THREAD THROWS. I used JJ on the final step of the whale, which gave me the answer and completed the area. In the Hub, I then guessed more rose rhymes; typing THREAD THROWS gave me the usual 'saved to THINK' spiel and this THINK text:

> DEBUG note--I forgot to clear THREAD THROWS somehow. It would be nice to know how and when this happened.

**Comment by andrewschultz** [comment]
Thanks for this bug report! Sorry for the excess text spilling out. (Though my programming side is glad I put that code in there.)

The fix was a matter of switching up the order of two if statements. So your bug reminded me of things to check elsewhere, and that will be useful going forward with my next in-comp update!

My test scripts missed this, as I only tried THREAD THROWS elsewhere.

Also, this bug alerted me to other test cases, namely if you used the rose and lute correctly and then used that phrase in a different location, later. So that was really nice to clean up.

(The code details are in the linked commits, if you're interested!)
